version: "3.2"

services: 
  web:
    container_name: app
    restart: always
    build: .
    ports: 
      - "3000:3000/tcp"
      - "3001:3001/udp"
    links: 
      - db:db
    volumes: 
      - .:/usr/src/app 
    depends_on:
      - db
  db:
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    restart: always
    ports: 
      - "3002:3002"
    expose: 
      - "3002"
    environment: 
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: project1
      MYSQL_TCP_PORT: 3002
    volumes: 
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d:ro
      
      
    